# Generated by Django 5.1.1 on 2024-10-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_rename_pets_pet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
