# Generated by Django 5.1.1 on 2024-10-21 11:40

import petstagram_project.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ImageField(
                upload_to="images",
                validators=[petstagram_project.photos.validators.validate_photo_size],
            ),
        ),
    ]
